FROM openjdk:8-jdk-alpine

VOLUME /tmp

ARG CLIENT_SERVER_READ_TIMEOUT_MILLIS_ARG=5000

ARG HYSTRIX_TIMEOUT_ENABLED_ARG=false
ARG HYSTRIX_TIMEOUT_MILLIS_ARG=1000

ARG HYSTRIX_REQUEST_VOLUME_THRESHOLD_ARG=20
ARG HYSTRIX_SLEEP_WINDOW_MILLIS_ARG=5000
ARG HYSTRIX_ERROR_THRESHOLD_PERCENTAGE_ARG=50

COPY build/docker/app.jar app.jar

ENV CLIENT_SERVER_READ_TIMEOUT_MILLIS=$CLIENT_SERVER_READ_TIMEOUT_MILLIS_ARG

ENV HYSTRIX_TIMEOUT_ENABLED=$HYSTRIX_TIMEOUT_ENABLED_ARG
ENV HYSTRIX_TIMEOUT_MILLIS=$HYSTRIX_TIMEOUT_MILLIS_ARG

ENV HYSTRIX_REQUEST_VOLUME_THRESHOLD=$HYSTRIX_REQUEST_VOLUME_THRESHOLD_ARG
ENV HYSTRIX_SLEEP_WINDOW_MILLIS=$HYSTRIX_SLEEP_WINDOW_MILLIS_ARG
ENV HYSTRIX_ERROR_THRESHOLD_PERCENTAGE=$HYSTRIX_ERROR_THRESHOLD_PERCENTAGE_ARG

RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]